<h1>Email Spam Detection</h1>

<h6>1 = Spam, 0 = Not Spam</h6>

In [0]:
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [3]:
from google.colab import files
uploaded = files.upload()

Saving emails.csv to emails.csv


In [0]:
df = pd.read_csv('emails.csv')

In [6]:
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [7]:
df.shape

(5728, 2)

In [9]:
#Column Names
df.columns

Index(['text', 'spam'], dtype='object')

In [0]:
#Check for duplicates and remove
df.drop_duplicates(inplace=True)

In [11]:
df.shape

(5695, 2)

In [12]:
#Missing/NaN data
df.isnull().sum()

text    0
spam    0
dtype: int64

In [13]:
#Download stopwords package
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [0]:
def process_text(text):

  #Remove punctuation, stopwords
  no_punc = [char for char in text if char not in string.punctuation]
  no_punc = ''.join(no_punc)

  #Return list of clean text words
  clean_words = [word for word in no_punc.split() if word.lower() not in stopwords.words('english')]

  return clean_words

In [27]:
#Tokenization

df['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [43]:
message4 = 'hello world hello hello world play'
message5 = 'test test test test one hello'

#bow = bag of words
#Convert text to matrix of token counts
bow4 = CountVectorizer(analyzer=process_text).fit_transform([[message4],[message5]])

#Unique words in sentences (2nd column)
print(bow4)

print(bow4.shape)

  (0, 0)	3
  (0, 4)	2
  (0, 2)	1
  (1, 0)	1
  (1, 3)	4
  (1, 1)	1
(2, 5)


In [0]:
messages_bow = CountVectorizer(analyzer=process_text).fit_transform(df['text'])

In [0]:
#Split the data 80% Training, 20% Testing
#Random state = 0 allows different results
X_train,X_test,y_train,y_test = train_test_split(messages_bow, df['spam'],test_size=0.2,random_state=0)

In [49]:
messages_bow.shape

(5695, 37229)

In [50]:
#Create and train Naive Bayes
classifier = MultinomialNB()

classifier.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

<h1>Predictions on training data</h1>


In [52]:
#Predictions on training data
print(classifier.predict(X_train))

#Actual target values
print(y_train.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [55]:
#Evaluate model on training data set

prediction = classifier.predict(X_train)
print(classification_report(y_train,prediction))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556



In [56]:
#Confusion Matrix
print(confusion_matrix(y_train,prediction))

[[3445   12]
 [   1 1098]]


In [58]:
#Accuracy on training data 99.7%
print(accuracy_score(y_train,prediction))

0.9971466198419666


<h1>Predictions on testing data</h1>

In [60]:
#Predictions on testing data
print(classifier.predict(X_test))

#Actual target values
print(y_test.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [61]:
#Evaluate model on training data set

prediction = classifier.predict(X_test)
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139



In [62]:
#Evaluate model on training data set

prediction = classifier.predict(X_test)
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139



In [64]:
#Accuracy on training data 99.2%
print(accuracy_score(y_test,prediction))

0.9920983318700615
